plugins {
    id 'com.android.application'
}

android {
    namespace 'com.team404bnf.quizvuln'
    compileSdk 35

    defaultConfig {
        applicationId "com.team404bnf.quizvuln"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "OPENROUTER_API_KEY", "\"${OPENROUTER_API_KEY}\""

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation libs.activity // Added this line
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // Retrofit + Gson
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.3'

    // MPAndroidChart
    implementation 'com.github.PhilJay:MPAndroidChart:3.1.0'

    // Lottie
    implementation 'com.airbnb.android:lottie:3.4.0'

    // Glide
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.1'

    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // Room components
    implementation "androidx.room:room-runtime:2.6.1"
    annotationProcessor "androidx.room:room-compiler:2.6.1"
    // Optional - for Room with LiveData or Flow
    implementation "androidx.room:room-ktx:2.6.1"

    //Confetti
    implementation 'com.github.jinatonic.confetti:confetti:1.1.2'

    // Gson
    implementation 'com.google.code.gson:gson:2.10.1'

    //Lottie animation
    implementation "com.airbnb.android:lottie:6.3.0"





}
